version: "3.8"

volumes:
  postgres_data: {}
  redis_data: {}

services:
  webapp:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "${WEBAPP_IP:-127.0.0.1}:${WEBAPP_PORT:-8000}:8000"
    environment:
      - POSTGRES_NAME=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    image: ${APP_CODENAME}-webapp-image:latest
    depends_on:
      - db
      - redis
    container_name: credittrack
    env_file: .env

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    container_name: postgres

  redis:
    image: redis
    environment:
      - REDIS_PASSWORD=yourpassword
    container_name: redis

  celery:
    build: .
    command: celery -A yourappname worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - POSTGRES_NAME=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    image: celery:app
    container_name: celery